//////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////
//////////////////////////Siege of Dragonspear////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////

//CREATURES

COPY ~Recorder/cre/X32Rec.cre~ ~override/X32Rec.cre~
  SAY NAME1 ~Recorder~
  SAY NAME2 ~Recorder~
  WRITE_ASCII 0x248 ~X32Rec~ #8  //override script
  WRITE_ASCII 0x280 ~X3Rec~ #32  //DV
  WRITE_ASCII 0x2cc ~X32Rec~ #8   //pre-joining dialogue file
//  WRITE_ASCII 0X34 ~RecordM~ #8   //small portrait, we do not have one right now, comment out.
 // WRITE_ASCII 0x3c ~RecordL~ #8   //medium portrait, we do not have one right now, comment out. 
  SAY BIO ~Recorder tells you about playing a flute in the streets gifted to her by a wandering troupe. The gold sums she raised she shared with her fellow orphans, until
  she saved enough to go to a proper college, with the help of the sponsorship of a priest of oghma who was moved by her dedication for knowledge. Recorder is not her true name, and she only smiles when you try to press for a real name.~
  SAY INITIAL_MEETING ~Wait.~ [X3RInn]
  SAY MORALE ~It's...all over.~ [X3RFear] 
  SAY HAPPY  ~That was impressive.~ [X3RHap]
  SAY UNHAPPY_ANNOYED ~Unbelievable.~ [X3RAnn]
  SAY UNHAPPY_SERIOUS ~What were you thinking?~ [X3RSer]
  SAY UNHAPPY_BREAKING_POINT ~~ [] 
  SAY LEADER ~We walk together.~ [X3RLead]
  SAY TIRED ~I must rest.~ [X3RRest]
  SAY BORED ~*Plays flute.*~ [X3RBored]
  SAY BATTLE_CRY1 ~Time for your final bow!~ [X3RCry1]
  SAY BATTLE_CRY2 ~Care for an encore?~ [X3RCry2]
  SAY BATTLE_CRY3 ~Don't be reckless!~ [X3RCry3]
  SAY BATTLE_CRY4 ~We won't lose!~ [X3RCry4]
  SAY BATTLE_CRY5 ~Rest in peace.~ [X3RCry5]
  SAY DAMAGE ~~ [X3RDam]
  SAY DYING ~~ [X3RDead]
  SAY HURT ~So this...is how it ends...~ [X3RHurt]
  SAY AREA_FOREST ~My heart is singing.~ [X3RFor]
  SAY AREA_CITY ~The songs you hear in cities are always so wonderful.~ []
  SAY AREA_DUNGEON ~We can do this.~ [X3RDun]
  SAY AREA_DAY ~Daybreak always brings new hope. And if you have long hair, more tangles.~ [X3RDay]
  SAY AREA_NIGHT ~Be careful.~ [X3RNight]
  SAY SELECT_COMMON1 ~Choose your path.~ [X3RCom1]
  SAY SELECT_COMMON2 ~I'm with you.~ [X3RCom2]
  SAY SELECT_COMMON3 ~Please, take your time.~ [X3RCom3]
  SAY SELECT_COMMON4 ~Go on.~ [X3RCom4]
  SAY SELECT_COMMON5 ~Hrm.~ [X3RCom5]
  SAY SELECT_COMMON6 ~Um...~ [X3RCom6]
  SAY SELECT_ACTION1 ~Ah, I see.~ [X3RAct1]
  SAY SELECT_ACTION2 ~Oh.~ [X3RAct2]
  SAY SELECT_ACTION3 ~We can see this through.~ [X3RAct3]
  SAY SELECT_ACTION4 ~I have faith in you.~ [X3RAct4]
  SAY SELECT_ACTION5 ~The path is yours to climb, but I'll help you on your way.~ [X3RAct5]
  SAY SELECT_ACTION6 ~I vow to bear you up, like a ship upon the waves, no matter what may come.~ [X3RAct6]
  SAY SELECT_ACTION7 ~If you'd like me to teach you a dance, you need simply ask.~ [X3RAct7]
  SAY CRITICAL_HIT ~It's over!~ [X3RCrit]
  SAY CRITICAL_MISS ~Goodness gracious!~ [X3RMiss]
  SAY TARGET_IMMUNE ~Oh my.~ [X3RImm]
  SAY INVENTORY_FULL ~I think not.~ [X3RInv]
  SAY SPELL_DISRUPTED ~My apologies.~ [X3RSpell]
  SAY SET_A_TRAP ~~ []
  SAY HIDDEN_IN_SHADOWS ~~ []
  SAY PICKED_POCKET ~~ []
  WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~X3Bard~)) 
  
APPEND ~bddialog.2da~ ~X3Rec X32Rec X32RecJ X32RecD~ 
  UNLESS ~X3Rec~


////////////////DIALOGUES

COMPILE EVALUATE_BUFFER ~Recorder/dialogue/SoD/X32Rec.d~
COMPILE EVALUATE_BUFFER ~Recorder/dialogue/SoD/X32RecJ.d~
COMPILE EVALUATE_BUFFER ~Recorder/dialogue/SoD/X32RCin.d~
COMPILE EVALUATE_BUFFER ~Recorder/dialogue/SoD/X32Run.d~
COMPILE EVALUATE_BUFFER ~Recorder/dialogue/SoD/X32RB1.d~


// Non-Area Scripts 
COMPILE EVALUATE_BUFFER ~Recorder/Scripts/SoD/X32Rec.baf~
COMPILE EVALUATE_BUFFER ~Recorder/Scripts/SoD/X32RBant.baf~
COMPILE EVALUATE_BUFFER ~Recorder/Scripts/SoD/X32RCin.baf~
COMPILE EVALUATE_BUFFER ~Recorder/Scripts/SoD/X32Run.baf~
  COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/Scripts/SOD/x3rcutg.baf~ 
  COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/Scripts/SOD/X32RB1.baf~ 
  COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/Scripts/SOD/X32RB2.baf~ 
  COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/Scripts/SOD/X32RB3.baf~ 
  COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/Scripts/SOD/X32RB4.baf~ 
  COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/Scripts/SOD/X32RB5.baf~ 
  COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/Scripts/SOD/X32RB6.baf~   
  EXTEND_TOP ~bdintro.bcs~ ~%MOD_FOLDER%/Scripts/SoD/bdintro.baf~
  EXTEND_TOP ~bdparty.bcs~ ~%MOD_FOLDER%/Scripts/SoD/bdparty.baf~
  EXTEND_TOP ~bdcut08.bcs~ ~%MOD_FOLDER%/Scripts/SoD/bdcut08.baf~   
   EXTEND_TOP ~bdcut58.bcs~ ~%MOD_FOLDER%/Scripts/SOD/bdcut58.baf~
  EXTEND_TOP ~bdcut59b.bcs~ ~%MOD_FOLDER%/Scripts/SOD/bdcut59b.baf~
  EXTEND_TOP ~bdcut61.bcs~ ~%MOD_FOLDER%/Scripts/SOD/bdcut61.baf~  
   
  

////////////////Area SCRIPTS
  EXTEND_TOP ~bd0010.bcs~ ~%MOD_FOLDER%/scripts/SoD/bd0010.baf~
  EXTEND_TOP ~bd0063.bcs~ ~%MOD_FOLDER%/scripts/SoD/bd0063.baf~  
  EXTEND_TOP ~bd0066.bcs~ ~%MOD_FOLDER%/scripts/SoD/bd0066.baf~   
  EXTEND_TOP ~bd0101.bcs~ ~%MOD_FOLDER%/scripts/SoD/bd0101.baf~ 
  EXTEND_TOP ~bd0103.bcs~ ~%MOD_FOLDER%/scripts/SoD/bd0103.baf~ 
  EXTEND_TOP ~bd0103.bcs~ ~%MOD_FOLDER%/scripts/SoD/bd0104.baf~  
  EXTEND_TOP ~bd0120.bcs~ ~%MOD_FOLDER%/scripts/SoD/bd0120.baf~  
  EXTEND_TOP ~bd1000.bcs~ ~%MOD_FOLDER%/scripts/SoD/bd1000.baf~ 
  EXTEND_TOP ~bd2000.bcs~ ~%MOD_FOLDER%/scripts/SoD/bd2000.baf~ 
  EXTEND_TOP ~bd3000.bcs~ ~%MOD_FOLDER%/scripts/SoD/bd3000.baf~ 
  EXTEND_TOP ~bd4300.bcs~ ~%MOD_FOLDER%/scripts/SoD/bd4300.baf~   
  EXTEND_TOP ~bd5300.bcs~ ~%MOD_FOLDER%/scripts/SoD/bd5300.baf~   
  EXTEND_TOP ~bd7100.bcs~ ~%MOD_FOLDER%/scripts/SoD/bd7100.baf~   
  EXTEND_TOP ~bd7300.bcs~ ~%MOD_FOLDER%/scripts/SoD/bd7300.baf~     

///////////////Other Creatures 
COPY ~%MOD_FOLDER%/cre/x32RCIN.cre~ ~override~
SAY NAME1 ~Cindy~
SAY NAME2 ~Cindy~
  WRITE_ASCII 0x248 ~X32RCIN~ #8  //override script
  WRITE_ASCII 0x280 ~X32RCIN~ #32  //DV
  WRITE_ASCII 0x2cc ~X32RCIN~ #8   //pre-joining dialogue file
  
COPY ~%MOD_FOLDER%/cre/X32RB1.cre~ ~override~
SAY NAME1 ~Bandit~
SAY NAME2 ~Bandit~
  WRITE_ASCII 0x248 ~X32RB1~ #8  //override script
  WRITE_ASCII 0x280 ~X32RB1~ #32  //DV
  WRITE_ASCII 0x2cc ~X32RB1~ #8   //pre-joining dialogue file
COPY ~%MOD_FOLDER%/cre/X32RB2.cre~ ~override~
SAY NAME1 ~Bandit~
SAY NAME2 ~Bandit~
  WRITE_ASCII 0x248 ~X32RB2~ #8  //override script
  WRITE_ASCII 0x280 ~X32RB2~ #32  //DV
  WRITE_ASCII 0x2cc ~X32RB2~ #8   //pre-joining dialogue file
COPY ~%MOD_FOLDER%/cre/X32RB3.cre~ ~override~
SAY NAME1 ~Bandit~
SAY NAME2 ~Bandit~
  WRITE_ASCII 0x248 ~X32RB3~ #8  //override script
  WRITE_ASCII 0x280 ~X32RB3~ #32  //DV
  WRITE_ASCII 0x2cc ~X32RB3~ #8   //pre-joining dialogue file
COPY ~%MOD_FOLDER%/cre/X32RB4.cre~ ~override~
SAY NAME1 ~Bandit~
SAY NAME2 ~Bandit~
  WRITE_ASCII 0x248 ~X32RB4~ #8  //override script
  WRITE_ASCII 0x280 ~X32RB4~ #32  //DV
  WRITE_ASCII 0x2cc ~X32RB4~ #8   //pre-joining dialogue file
COPY ~%MOD_FOLDER%/cre/X32RB5.cre~ ~override~
SAY NAME1 ~Bandit~
SAY NAME2 ~Bandit~
  WRITE_ASCII 0x248 ~X32RB5~ #8  //override script
  WRITE_ASCII 0x280 ~X32RB5~ #32  //DV
  WRITE_ASCII 0x2cc ~X32RB5~ #8   //pre-joining dialogue file
COPY ~%MOD_FOLDER%/cre/X32RB6.cre~ ~override~
SAY NAME1 ~Bandit~
SAY NAME2 ~Bandit~
  WRITE_ASCII 0x248 ~X32RB6~ #8  //override script
  WRITE_ASCII 0x280 ~X32RB6~ #32  //DV
  WRITE_ASCII 0x2cc ~X32RB6~ #8   //pre-joining dialogue file  
  