
IF
	Global("BD_AREA_HOSTILE","BD5300",1)
	!GlobalTimerNotExpired("bd_sdd350b_ot_timer","bd2000")
	Global("bd_ot_X3Rec","bd5300",0)
	IsValidForPartyDialog("X3Rec")   
	TriggerOverride("X3Rec",Range([ENEMY.0.0.0.HOSTILES3],30))
THEN
	RESPONSE #100
		SetGlobalTimer("bd_sdd350b_ot_timer","bd2000",THREE_MINUTES)
		SetGlobal("bd_ot_X3Rec","bd5300",1)
		DisplayStringHead("X3Rec",~Your story ends today!~) 
END

